//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDSharp {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDDSharp.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Analysing Parameters files(*.analyze)|*.analyze 的本地化字符串。
        /// </summary>
        internal static string AnalyzeParametersStructerFilter {
            get {
                return ResourceManager.GetString("AnalyzeParametersStructerFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bitmap File (*.bmp;*.jpg;*.gif;*.png)|*.bmp;*.jpg;*.gif;*.png 的本地化字符串。
        /// </summary>
        internal static string BitmapFileFilter {
            get {
                return ResourceManager.GetString("BitmapFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boreholes Control File (*.csv,*.dat,*.txt)|*.csv;*.dat;*.txt 的本地化字符串。
        /// </summary>
        internal static string BoreholeInterpolationControlFile {
            get {
                return ResourceManager.GetString("BoreholeInterpolationControlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 formatted line files(*.csv,*.dat,*.txt)|*.csv;*.dat;*.txt 的本地化字符串。
        /// </summary>
        internal static string BoreholesInclinesFileFormatFilter {
            get {
                return ResourceManager.GetString("BoreholesInclinesFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ColorPicker {
            get {
                object obj = ResourceManager.GetObject("ColorPicker", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 DXF File (*.dxf)|*.dxf 的本地化字符串。
        /// </summary>
        internal static string DXFFileFormatFilter {
            get {
                return ResourceManager.GetString("DXFFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Folder01 {
            get {
                object obj = ResourceManager.GetObject("Folder01", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 formatted LAS files(*.csv,*.dat,*.txt)|*.csv;*.dat;*.txt 的本地化字符串。
        /// </summary>
        internal static string FormatLASControlFileFilter {
            get {
                return ResourceManager.GetString("FormatLASControlFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 formatted LAS files(*.las)|*.las 的本地化字符串。
        /// </summary>
        internal static string FormatLASFileFilter {
            get {
                return ResourceManager.GetString("FormatLASFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geological Project File (*.g3d)|*.g3d 的本地化字符串。
        /// </summary>
        internal static string G3dProjectFileFilter {
            get {
                return ResourceManager.GetString("G3dProjectFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formatted Geological Mesh File (*.gmesh)|*.gmesh 的本地化字符串。
        /// </summary>
        internal static string GeoMeshFileFormatFilter {
            get {
                return ResourceManager.GetString("GeoMeshFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Grid3D {
            get {
                object obj = ResourceManager.GetObject("Grid3D", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 3D Grid file(*.3DGrid)|*.3DGrid 的本地化字符串。
        /// </summary>
        internal static string Grid3DFileFormatFilter {
            get {
                return ResourceManager.GetString("Grid3DFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images File(*.jpg,*.png,*.bmp,*.gif,*.tif)|*.jpg;*.png;*.bmp;*.gif;*.tif|all files(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string ImageFilesFormatFilter {
            get {
                return ResourceManager.GetString("ImageFilesFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formatted Line File (*.line)|*.line 的本地化字符串。
        /// </summary>
        internal static string LineFileFormatFilter {
            get {
                return ResourceManager.GetString("LineFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formatted Mesh File (*.mesh)|*.mesh 的本地化字符串。
        /// </summary>
        internal static string MeshFileFormatFilter {
            get {
                return ResourceManager.GetString("MeshFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OBJ 3D Triangles File (*.obj)|*.obj 的本地化字符串。
        /// </summary>
        internal static string OBJFileFormatedFilter {
            get {
                return ResourceManager.GetString("OBJFileFormatedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLY 3D Triangles File (*.ply)|*.ply 的本地化字符串。
        /// </summary>
        internal static string PLYFileFormatedFilter {
            get {
                return ResourceManager.GetString("PLYFileFormatedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formatted Polygon File (*.polycer)|*.polycer 的本地化字符串。
        /// </summary>
        internal static string PoligonSlicerFileFormatFilter {
            get {
                return ResourceManager.GetString("PoligonSlicerFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formatted Polygon2D File (*.poly2d)|*.poly2d 的本地化字符串。
        /// </summary>
        internal static string Polygon2DFileFormatFilter {
            get {
                return ResourceManager.GetString("Polygon2DFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon PolygonSlicer {
            get {
                object obj = ResourceManager.GetObject("PolygonSlicer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Polygon3D XYZ(*.csv,*.dat,*.txt)|*.csv;*.dat;*.txt 的本地化字符串。
        /// </summary>
        internal static string PolygonSlicerPoly3DXYZ {
            get {
                return ResourceManager.GetString("PolygonSlicerPoly3DXYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SHP File (*.shp)|*.shp 的本地化字符串。
        /// </summary>
        internal static string SHPFileFormatFilter {
            get {
                return ResourceManager.GetString("SHPFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formatted Slicer File (*.slicer)|*.slicer 的本地化字符串。
        /// </summary>
        internal static string SlicerFileFormatFilter {
            get {
                return ResourceManager.GetString("SlicerFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STL 3D Triangles File (*.stl)|*.stl 的本地化字符串。
        /// </summary>
        internal static string STLFileFormatedFilter {
            get {
                return ResourceManager.GetString("STLFileFormatedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 formatted line files(*.StratumColor,*.dat,*.txt)|*.StratumColor;*.dat;*.txt 的本地化字符串。
        /// </summary>
        internal static string StratumColorSchemeFilter {
            get {
                return ResourceManager.GetString("StratumColorSchemeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Surfer gridded File (*.grd)|*.grd 的本地化字符串。
        /// </summary>
        internal static string SurferGridFileFormatFilter {
            get {
                return ResourceManager.GetString("SurferGridFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formatted Triangles File (*.ply,*.obj,*.stl)|*.ply;*.obj;*.stl 的本地化字符串。
        /// </summary>
        internal static string TriangleFileFormatFilter {
            get {
                return ResourceManager.GetString("TriangleFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VRML Model File *.wrl|*.wrl 的本地化字符串。
        /// </summary>
        internal static string VRMLFileFormatFilter {
            get {
                return ResourceManager.GetString("VRMLFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Borehole welling data file(*.las)|*.las 的本地化字符串。
        /// </summary>
        internal static string WellingCurveDataFilter {
            get {
                return ResourceManager.GetString("WellingCurveDataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Borehole well stratum files(*.csv,*.dat,*.txt)|*.csv;*.dat;*.txt 的本地化字符串。
        /// </summary>
        internal static string WellStratumDataFilter {
            get {
                return ResourceManager.GetString("WellStratumDataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XYZV ACSII File (*.pcd,*.vtk,*.csv,*.dat,*.txt)|*.pcd;*.vtk;*.pnts;*.csv;*.dat;*.txt; 的本地化字符串。
        /// </summary>
        internal static string XYZVFileFormatFilter {
            get {
                return ResourceManager.GetString("XYZVFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 formatted line files(*.csv,*.dat,*.txt)|*.csv;*.dat;*.txt 的本地化字符串。
        /// </summary>
        internal static string XYZVFormatLineFilter {
            get {
                return ResourceManager.GetString("XYZVFormatLineFilter", resourceCulture);
            }
        }
    }
}
