//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDDSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDDSharp.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap File (*.bmp;*.jpg;*.gif;*.png)|*.bmp;*.jpg;*.gif;*.png.
        /// </summary>
        internal static string BitmapFileFilter {
            get {
                return ResourceManager.GetString("BitmapFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXF File (*.dxf)|*.dxf.
        /// </summary>
        internal static string DXFFileFormatFilter {
            get {
                return ResourceManager.GetString("DXFFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Folder01 {
            get {
                object obj = ResourceManager.GetObject("Folder01", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formatted LAS files(*.csv,*.dat,*.txt)|*.csv;*.dat;*.txt.
        /// </summary>
        internal static string FormatLASControlFileFilter {
            get {
                return ResourceManager.GetString("FormatLASControlFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formatted LAS files(*.las)|*.las.
        /// </summary>
        internal static string FormatLASFileFilter {
            get {
                return ResourceManager.GetString("FormatLASFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geological Project File (*.g3d)|*.g3d.
        /// </summary>
        internal static string G3dProjectFileFilter {
            get {
                return ResourceManager.GetString("G3dProjectFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Geological Mesh File (*.gmesh)|*.gmesh.
        /// </summary>
        internal static string GeoMeshFileFormatFilter {
            get {
                return ResourceManager.GetString("GeoMeshFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Grid3D {
            get {
                object obj = ResourceManager.GetObject("Grid3D", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Grid file(*.3DGrid)|*.3DGrid.
        /// </summary>
        internal static string Grid3DFileFormatFilter {
            get {
                return ResourceManager.GetString("Grid3DFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Line File (*.line)|*.line.
        /// </summary>
        internal static string LineFileFormatFilter {
            get {
                return ResourceManager.GetString("LineFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Mesh File (*.mesh)|*.mesh.
        /// </summary>
        internal static string MeshFileFormatFilter {
            get {
                return ResourceManager.GetString("MeshFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJ 3D Triangles File (*.obj)|*.obj.
        /// </summary>
        internal static string OBJFileFormatedFilter {
            get {
                return ResourceManager.GetString("OBJFileFormatedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLY 3D Triangles File (*.ply)|*.ply.
        /// </summary>
        internal static string PLYFileFormatedFilter {
            get {
                return ResourceManager.GetString("PLYFileFormatedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Polygon File (*.polycer)|*.polycer.
        /// </summary>
        internal static string PoligonSlicerFileFormatFilter {
            get {
                return ResourceManager.GetString("PoligonSlicerFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Polygon2D File (*.poly2d)|*.poly2d.
        /// </summary>
        internal static string Polygon2DFileFormatFilter {
            get {
                return ResourceManager.GetString("Polygon2DFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon PolygonSlicer {
            get {
                object obj = ResourceManager.GetObject("PolygonSlicer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHP File (*.shp)|*.shp.
        /// </summary>
        internal static string SHPFileFormatFilter {
            get {
                return ResourceManager.GetString("SHPFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Slicer File (*.slicer)|*.slicer.
        /// </summary>
        internal static string SlicerFileFormatFilter {
            get {
                return ResourceManager.GetString("SlicerFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STL 3D Triangles File (*.stl)|*.stl.
        /// </summary>
        internal static string STLFileFormatedFilter {
            get {
                return ResourceManager.GetString("STLFileFormatedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surfer gridded File (*.grd)|*.grd.
        /// </summary>
        internal static string SurferGridFileFormatFilter {
            get {
                return ResourceManager.GetString("SurferGridFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Triangles File (*.ply,*.obj,*.stl)|*.ply;*.obj;*.stl.
        /// </summary>
        internal static string TriangleFileFormatFilter {
            get {
                return ResourceManager.GetString("TriangleFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRML Model File *.wrl|*.wrl.
        /// </summary>
        internal static string VRMLFileFormatFilter {
            get {
                return ResourceManager.GetString("VRMLFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borehole welling data file(*.las)|*.las.
        /// </summary>
        internal static string WellingCurveDataFilter {
            get {
                return ResourceManager.GetString("WellingCurveDataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borehole well stratum files(*.csv,*.dat,*.txt)|*.csv;*.dat;*.txt.
        /// </summary>
        internal static string WellStratumDataFilter {
            get {
                return ResourceManager.GetString("WellStratumDataFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XYZV ACSII File (*.csv,*.dat,*.txt)|*.csv;*.dat;*.txt;.
        /// </summary>
        internal static string XYZVFileFormatFilter {
            get {
                return ResourceManager.GetString("XYZVFileFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formatted line files(*.csv,*.dat,*.txt)|*.csv;*.dat;*.txt.
        /// </summary>
        internal static string XYZVFormatLineFilter {
            get {
                return ResourceManager.GetString("XYZVFormatLineFilter", resourceCulture);
            }
        }
    }
}
